//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationDetails
    {
        public int DetailID { get; set; }
        public int OperationID { get; set; }
        public int ProductID { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual WarehouseOperations WarehouseOperations { get; set; }
        public virtual Products Products { get; set; }
    }
}
