//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseOperations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseOperations()
        {
            this.OperationDetails = new HashSet<OperationDetails>();
        }
    
        public int OperationID { get; set; }
        public string OperationType { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationDetails> OperationDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Users Users { get; set; }
    }
}
